### PR TITLE
Update electrum to 4.5.2

### PR DESCRIPTION
**Pull request by renothing**

### CODE REVIEW

**Comment by A6GibKm** [comment]
Thanks! Please test the app and drop a small message if it looks ok and Ill merge it later today, please ping me if I forget today.

**Comment by renothing** [comment]
> Thanks! Please test the app and drop a small message if it looks ok and Ill merge it later today, please ping me if I forget today.

Hi there, yes, it works fine on my x86 pc

**Comment by A6GibKm** [comment]
Thanks, due to a problem with the flathub runner I cannot press merge (it will fix itself in a few hours). Once thats done ill merge it.

**Comment by bbhtt** [comment]
bot, build

**Comment by A6GibKm** [comment]
Thanks!

**Pull request merged**
